name: Data Issue Report
description: Prijavi problem sa podacima
labels: ["data"]
projects: ["Rjecnik-Data"]
body:
  - type: input
    id: rijec
    attributes:
      label: Rijec
      description: Rijec prijavljujete gresku
      placeholder: npr. aba
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: url
      description: Url rijeci za koju prijavljujete gresku
      placeholder: npr. {url}/rijec/1
    validations:
      required: false
  - type: textarea
    id: definicija
    attributes:
      label: Definicija rijeci
      description: Definicija rijeci za koju prijavljujete gresku
      render: shell
  - type: markdown
    attributes:
      value: "Padezi ili glagolska vremena"
