create type public.app_permission as enum ('Dictionary.ReadWrite');

create table public.user_permissions (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  permission      app_permission not null,
  unique (user_id, permission)
);

-- Create the auth hook function
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
  declare
    claims jsonb;
    user_permission public.app_permission;
  begin
    -- Fetch the user role in the user_roles table
    select permission into user_permission from public.user_permissions where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_permission is not null then
      -- Set the claim
      claims := jsonb_set(claims, '{user_permission}', to_jsonb(user_permission));
    else
      claims := jsonb_set(claims, '{user_permission}', 'null');
    end if;

    -- Update the 'claims' object in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the modified or original event
    return event;
  end;
$$;

grant usage on schema public to supabase_auth_admin;

grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;

revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon, public;

grant all
  on table public.user_permissions
to supabase_auth_admin;

revoke all
  on table public.user_permissions
  from authenticated, anon, public;

create policy "Allow auth admin to read user permissions" ON public.user_permissions
as permissive for select
to supabase_auth_admin
using (true)
